export enum PlayerPosition {
  PORTERO = 'Portero',
  PORTERA = 'Portera',
  DEFENSA_LATERAL_DERECHO = 'Defensa Lateral Derecho',
  DEFENSA_LATERAL_IZQUIERDO = 'Defensa Lateral Izquierdo',
  DEFENSA_CENTRAL = 'Defensa Central',
  DEFENSA = 'Defensa',
  VOLANTE_IZQUIERDO_EXTREMO = 'Volante Izquierdo Extremo',
  VOLANTE_IZQUIERDO = 'Volante Izquierdo',
  VOLANTE_DERECHO_EXTREMO = 'Volante Derecho Extremo',
  VOLANTE_DERECHO = 'Volante Derecho',
  MEDIO_CENTRO_DERECHO = 'Medio Centro Derecho',
  MEDIO_CENTRO_IZQUIERDO = 'Medio Centro Izquierdo',
  MEDIO_CENTRO = 'Medio Centro',
  MEDIA_PUNTA = 'Media Punta',
  DELANTERO_CENTRO = 'Delantero Centro',
  DELANTERA_CENTRO = 'Delantera Centro',
  DELANTERO_IZQUIERDO = 'Delantero Izquierdo',
  DELANTERO_DERECHO = 'Delantero Derecho',
}

export enum PlayerPositionAbbreviation {
  PO = 'PO',
  DFC = 'DFC',
  DFI = 'DFI',
  DFD = 'DFD',
  DF = 'DF',
  VIE = 'VIE',
  VI = 'VI',
  VDE = 'VDE',
  VD = 'VD',
  MC = 'MC',
  MCD = 'MCD',
  MCI = 'MCI',
  MI = 'MI',
  MD = 'MD',
  MP = 'MP',
  DC = 'DC',
  DI = 'DI',
  DD = 'DD',
}
