export enum Permission {
  // Permisos de Usuario
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  MANAGE_ROLES = 'MANAGE_ROLES',

  // Permisos de Liga
  CREATE_LEAGUE = 'CREATE_LEAGUE',
  READ_LEAGUE = 'READ_LEAGUE',
  UPDATE_LEAGUE = 'UPDATE_LEAGUE',
  DELETE_LEAGUE = 'DELETE_LEAGUE',
  MANAGE_LEAGUE_SETTINGS = 'MANAGE_LEAGUE_SETTINGS',

  // Permisos de Equipo
  CREATE_TEAM = 'CREATE_TEAM',
  READ_TEAM = 'READ_TEAM',
  UPDATE_TEAM = 'UPDATE_TEAM',
  DELETE_TEAM = 'DELETE_TEAM',
  MANAGE_TEAM_PLAYERS = 'MANAGE_TEAM_PLAYERS',

  // Permisos de Jugador
  CREATE_PLAYER = 'CREATE_PLAYER',
  READ_PLAYER = 'READ_PLAYER',
  UPDATE_PLAYER = 'UPDATE_PLAYER',
  DELETE_PLAYER = 'DELETE_PLAYER',

  // Permisos de Partido
  CREATE_MATCH = 'CREATE_MATCH',
  READ_MATCH = 'READ_MATCH',
  UPDATE_MATCH = 'UPDATE_MATCH',
  DELETE_MATCH = 'DELETE_MATCH',
  REPORT_MATCH_RESULT = 'REPORT_MATCH_RESULT',

  // Permisos de Contenido
  MANAGE_IMAGES = 'MANAGE_IMAGES',
  MANAGE_NEWS = 'MANAGE_NEWS',
  PUBLISH_CONTENT = 'PUBLISH_CONTENT',
}
